# Generated by Django 3.0.7 on 2020-06-27 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccforCus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountid', models.CharField(db_column='accountID', max_length=6, primary_key=True, serialize=False)),
                ('money', models.FloatField()),
                ('settime', models.DateTimeField()),
                ('accounttype', models.CharField(choices=[('saveacc', '储蓄账户'), ('checkacc', '支票账户')], max_length=10)),
            ],
            options={
                'db_table': 'accounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bankname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('money', models.FloatField()),
            ],
            options={
                'db_table': 'bank',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cusid', models.CharField(db_column='cusID', max_length=18, primary_key=True, serialize=False)),
                ('cusname', models.CharField(max_length=10)),
                ('cusphone', models.CharField(max_length=11)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(max_length=11)),
                ('contact_email', models.CharField(blank=True, db_column='contact_Email', max_length=20, null=True)),
                ('relation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departid', models.CharField(db_column='departID', max_length=4, primary_key=True, serialize=False)),
                ('departname', models.CharField(max_length=20)),
                ('departtype', models.CharField(blank=True, max_length=15, null=True)),
                ('bank', models.ForeignKey(db_column='bank', on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanid', models.CharField(db_column='loanID', max_length=4, primary_key=True, serialize=False)),
                ('money', models.FloatField(blank=True, null=True)),
                ('settime', models.DateTimeField()),
                ('state', models.CharField(blank=True, default='0', max_length=1, null=True)),
                ('bank', models.ForeignKey(db_column='bank', on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
                ('loanforcus', models.ManyToManyField(related_name='loanforcus', to='bank.Customer')),
            ],
            options={
                'db_table': 'loan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checkacc',
            fields=[
                ('accountid', models.OneToOneField(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.Accounts')),
                ('overdraft', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checkacc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Saveacc',
            fields=[
                ('accountid', models.OneToOneField(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.Accounts')),
                ('interestrate', models.FloatField(blank=True, null=True)),
                ('savetype', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'saveacc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, null=True)),
                ('paytime', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Loan')),
            ],
            options={
                'unique_together': {('loan', 'customer', 'money', 'paytime')},
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='pay_info',
            field=models.ManyToManyField(related_name='pay_info', through='bank.Payinfo', to='bank.Customer'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(db_column='empID', max_length=18, primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=20)),
                ('empphone', models.CharField(blank=True, max_length=11, null=True)),
                ('empaddr', models.CharField(blank=True, max_length=50, null=True)),
                ('emptype', models.CharField(blank=True, choices=[('manager', '部门经理'), ('staff', '普通员工')], max_length=10, null=True)),
                ('empstart', models.DateField()),
                ('depart', models.ForeignKey(db_column='depart', on_delete=django.db.models.deletion.CASCADE, to='bank.Department')),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='accres',
            field=models.ForeignKey(blank=True, db_column='accres', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accres', to='bank.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loanres',
            field=models.ForeignKey(blank=True, db_column='loanres', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanres', to='bank.Employee'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='bank',
            field=models.ForeignKey(db_column='bank', on_delete=django.db.models.deletion.CASCADE, to='bank.Bank'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='customer',
            field=models.ManyToManyField(related_name='account', through='bank.AccforCus', to='bank.Customer'),
        ),
        migrations.AddField(
            model_name='accforcus',
            name='accounts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Accounts'),
        ),
        migrations.AddField(
            model_name='accforcus',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Customer'),
        ),
        migrations.AlterUniqueTogether(
            name='accforcus',
            unique_together={('accounts', 'customer')},
        ),
    ]
